### ISSUE TITLE
AutoRangePadding changes data point values instead of increasing axis range

### ISSUE THREAD

**Issue by roberto0013** [GSI-CS-CO/chart-fx#469]
**Describe the bug**
In the newly released version 11.2.6 when adding AutoRangePadding to an Axis the axis range isn't increased instead the shown data-points changes value.
![image](https://user-images.githubusercontent.com/61186432/141325933-91a8edb5-5b23-4a41-ba17-01a19defd749.png)
A sine-curve with the amplitude 40 and no padding.
![image](https://user-images.githubusercontent.com/61186432/141326066-1f6e59fa-92cc-4157-924d-0b169d2f5cb3.png)
The same sine-curve but with 0.3 (30%) padding. As can clearly be seen the axis-range doesn't increase, instead the sine-waves amplitude is decreased.

**To Reproduce**
The problem is visible in the PaddedAutoGrowAxisSample.java, but can also be reproduced by creating a simple sine-wave and adding AutoRangePadding.
 
``` java
public class TimeChartTester extends Application{
    @Override
    public void start(final Stage aPrimaryStage) throws Exception {
        final var xAxis = new DefaultNumericAxis();
        final var yAxis = new DefaultNumericAxis();
        final var chart = new XYChart(xAxis, yAxis);
        chart.getPlugins().add(new EditAxis());
        chart.getPlugins().add(new Zoomer());

        yAxis.setAutoRangePadding(0.3);
        yAxis.setAutoRanging(false);
        yAxis.setAutoGrowRanging(true);
        yAxis.set(0, 10);

        final var ds = new CircularDoubleErrorDataSet("", 150);
        chart.getDatasets().addAll(ds);
                for (int i = 0; i < 500; i++) {
                    ds.add(i, 40 * Math.sin(i * 0.1), 0, 0);
                    }

        final Scene scene = new Scene(chart, 800, 600);
        aPrimaryStage.setScene(scene);
        aPrimaryStage.show();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(final String[] args) {
        Application.launch(args);
    }
}
```

**Environment:**
 - OS: Windows
 - Java version: 11
 - JavaFx version: 11.0.2
 - ChartFx version: 11.2.6

**Comment by wirew0rm** [comment]
Hey, thanks for the bug report.

In #466 we fixed another problem with the combination of autoGrowRanging and axisPadding. Did you take a look at that PR and the sample submitted with it? I'm away from my IDE at the moment, but from looking at the code, the main difference seems to be that you add the data and then only afterwards add the chart to the scenegraph.

What probably happens is that the axis is drawn and only afterwards rescaled to the data range and this new (correct) range is used for rendering the sine wave.
As  a workaround you can probably manually trigger an update using `requestLayout` on the chart or axis but this should not be necessary, we'll have to look into it, at the moment I'm not sure what caused the correct redraw before the change.

**Comment by roberto0013** [comment]
Hello, thanks for the fast response.

Just to clarify, the problem is still present when running the provided PaddedAutoGrowAxisSample.java. So the difference between the implementations should not be the reason for the error. 
Perhaps you are right that there are some type of update that has to be triggered, I however did try to perform requestLayout/requestAxisLayout on both the chart and axes with no effect.

**Comment by wirew0rm** [comment]
Indeed, the rendering of the axis tickmarks doesn't seem to take the padding into account. Previously this was not a problem, because the padding was applied to the general axis limits, but this lead to other problems. I'll try to come up with a fix for this.

**Comment by wirew0rm** [comment]
solved in #470
